---
abstract: 'High-performance, dynamic web site authoring system'
author:
  - 'Jonathan Swartz <swartz@pobox.com>'
  - 'Dave Rolsky <autarch@urth.org>'
  - 'Ken Williams <ken@mathforum.org>'
build_requires:
  Test::Deep: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Mason
no_index:
  directory:
    - eg
  file:
    - lib/HTML/Mason/Tests.pm
requires:
  CGI: 2.46
  Cache::Cache: 1.00
  Class::Container: 0.07
  Exception::Class: 1.15
  File::Spec: 0.8
  HTML::Entities: 0
  Log::Any: 0.08
  Params::Validate: 0.70
  Scalar::Util: 1.01
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=HTML::Mason
  repository: git://github.com/jonswar/perl-HTML-Mason.git
version: 1.53
